Post APIの作成、Get APIの拡充 #4 #6
think-book/BookBasket-Server pull request #7
Opened 2019-06-22 12:10 UTC by noborack74

Close #4
Close #6 

内容
postができるようにしました。
getで、ISBNで本の詳細が取れるようにしました。
JSONをGo内部で構造体で管理するようにしました。
テストコードを追加しました。

2019-06-22 18:53 UTC, arkark requested changes
```sh
$ curl -X POST -H "Content-Type: application/json" -d '{"ISBN": 500, "title": "test title"}' localhost:8080/books
```
のコマンドを何度も実行するとISBN`500`のメタ情報が重複して入ってしまうので、すでにそのISBNのメタ情報が入ってる場合はBadRequestを返すようにしたほうが良さそう

`POST localhost:8080/books/:ISBN`のAPIについても、同じISBNのリクエストが来たときにBadRequestを返すべきかな

2019-06-22 18:53 UTC, ArkArk commented on handler/handler.go
> +	isbn, _ := strconv.Atoi(c.Param("ISBN"))
`c.Param("ISBN")`が数字ではなく`"text"`みたいな文字列だとエラーが発生するので、
エラーハンドリングをした方が良い。

```go
isbn, err := strconv.Atoi(c.Param("ISBN"))
if err != nil {
  // BadRequestを返す
}
```

2019-06-22 18:53 UTC, ArkArk commented on handler/handler.go
> +	isbn, _ := strconv.Atoi(c.Param("ISBN"))
ここも同様にエラーハンドリング

2019-06-25 03:01 UTC, noborack74 commented on handler/handler.go
> +	isbn, _ := strconv.Atoi(c.Param("ISBN"))
諸々対応しました。

2019-06-25 05:27 UTC, arkark approved these changes

2019-06-25 05:28 UTC, merged